default: &default
  adapter: mysql2
  encoding: utf8
  collation: utf8_general_ci

development:
  <<: *default
  database: reversi-dev
  username: root
  password:

test:
  <<: *default
  host: 127.0.0.1
  database: reversi-test
  username: root
  password:

production:
  <<: *default
  adapter: postgresql
  database: reversi-prod
  encoding: unicode
  pool: 5
